name: shared_preferences_gen

packages:
  - packages/**

ide:
  intellij: false

scripts:
  test:
    run: melos exec -- "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test

  gen:example:
    description: Run `dart run build_runner build --delete-conflicting-outputs` in the example package.
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    packageFilters:
      dependsOn:
        - build_runner
        - shared_preferences_gen

  coverage:
    run: melos exec -- "flutter test --coverage"
    description: Run `flutter test --coverage` for a specific package.
    packageFilters:
      dirExists:
        - test
