name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  shared_preferences_annotation:
    path: ../../shared_preferences_annotation

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  shared_preferences_gen:
    path: ../

flutter:
  uses-material-design: true
