name: shared_preferences_annotation
description: "Annotations for the shared_preferences_gen code-generator. This package does nothing without shared_preferences_gen too."

homepage: https://github.com/Ahnaf16/shared_preferences_gen
repository: https://github.com/Ahnaf16/shared_preferences_gen/tree/main/packages/shared_preferences_annotation
topics:
  - codegen
  - build-runner
  - shared-preferences

publish_to: none

version: 0.2.0

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.1.1
