name: shared_preferences_annotation
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/TesteurManiak/shared_preferences_gen

environment:
  sdk: ">=3.4.1 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
