name: shared_preferences_annotation
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/TesteurManiak/shared_preferences_gen

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
