builders:
  shared_preferences_gen:
    import: "package:shared_preferences_gen/shared_preferences_gen.dart"
    builder_factories: ["sharedPreferencesGen"]
    build_extensions: { ".dart": ["shared_preferences_gen.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
