name: shared_preferences_gen
description: "A code generator that provides strongly-typed accessors for Flutter shared_preferences entries."

homepage: https://github.com/Ahnaf16/shared_preferences_gen
repository: https://github.com/Ahnaf16/shared_preferences_gen/tree/main/packages/shared_preferences_gen
issue_tracker: https://github.com/Ahnaf16/shared_preferences_gen/issues
topics:
  - codegen
  - build-runner
  - shared-preferences

publish_to: none

version: 0.3.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <8.1.1"
  build: ^2.4.2
  source_gen: ^2.0.0
  source_helper: ^1.3.5
  shared_preferences_annotation:
    git:
      url: https://github.com/Ahnaf16/shared_preferences_gen.git
      path: packages/shared_preferences_annotation
      ref: fixing

dev_dependencies:
  lints: ^5.1.1
