name: shared_preferences_gen
description: "Typesafe code generation for Flutter shared_preferences."
version: 0.0.1
homepage: https://github.com/TesteurManiak/shared_preferences_gen
repository: https://github.com/TesteurManiak/shared_preferences_gen/tree/main/packages/shared_preferences_gen
topics:
  - codegen
  - build-runner
  - shared-preferences
publish_to: "none"

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  analyzer: ">=5.2.0 <7.0.0"
  build: ^2.4.1
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dev_dependencies:
  lints: ^4.0.0
